### PR TITLE
Update dictionary.html

### PR DESCRIPTION
**Pull request by peter1000**

### CODE REVIEW

**Comment by peter1000** [comment]
Personally I think the part about: **A scenario** should be removed or completely rewritten. To me it does not seem to fit with the style of the rest.

**Comment by tnut** [comment]
You probably right, It was translate without technical point of view, please feel free. It's should stay in the dictionnary as it's  a recurrant word on the nutyx.org web site

**Comment by peter1000** [comment]
A other problem I saw is: in **The 'Pkgfile' file** you say that there are `Mandatory information`: for the construction of the package: Name, version, release

But in groups they are not set except in the main Pkgfile

**Comment by peter1000** [comment]
example of: no version  https://github.com/NuTyX/core/blob/master/gui/gstreamer1-plugins-bad/Pkgfile

Personally I think it would be best to require it for all Pkgfiles.

**Comment by peter1000** [comment]
The *group part* does not specify what is so special about it: only that they begin with the same name :-1:

**Comment by tnut** [comment]
What I forgot to mention is that packages from the same group shares
variables value. For exemple, when we have to upgrade kf5-* packages we
only need to update the kf5 package, as variable version is common

2016-04-08 15:01 GMT+02:00 peter1000 <notifications@github.com>:

**Comment by peter1000** [comment]
Just to clarify: from the code it seems that they share all variables - not only 'version' is that correct?

Point 2: is that the only difference for groups or are they also special when they get installed?

**Pull request merged**
