### PR TITLE
update base - cli and gui and problem with samba 4.4.2

### PR DESCRIPTION
**Pull request by fanch**
this is my second update series of the week. Can you control samba 4.4.2 ? i haven't problem to build it but if i can't install samba.devel.

### CODE REVIEW

**Comment by fanch** [comment]
samba : problem of dependances

**Comment by tnut** [comment]
this commit cannot be merge: Error (xorg), missing changes (wget_nutyx), comflict and samba problem (original issue) not solved

**Comment by fanch** [comment]
it's ok, i take off tdb in dependance because redondance.

**Comment by tnut** [comment]
Thanks for your commit, I will commit one by one and when it's done
close the Pull Request

**Pull request closed without merging**
